version: "3.8"
services:
  nextjs:
    depends_on: [mongodb]
    container_name: ${ENV_NAME}_jsouchet_nextjs
    hostname: ${ENV_NAME}_jsouchet_nextjs
    build: ./app
    ports:
      - "${NEXTJS_PORT}:3001"
    environment:
      NODE_ENV: developpement
    volumes:
      - "./app:/home/app"
  mongodb:
    container_name: ${ENV_NAME}_jsouchet_mongodb
    hostname: ${ENV_NAME}_jsouchet_mongodb
    build: ./db
    ports:
      - "${MONGODB_PORT}:27017"