version: "3.8"
services:
  nextjs:
    depends_on: [mongodb]
    container_name: ${ENV_NAME}_jsouchet_nextjs
    hostname: ${ENV_NAME}_jsouchet_nextjs
    build: ./client
    ports:
      - "${NEXTJS_PORT}:3001"
    networks:
      - test_network
  mongodb:
    container_name: ${ENV_NAME}_jsouchet_mongodb
    hostname: ${ENV_NAME}_jsouchet_mongodb
    build: ./db
    ports:
      - "${MONGODB_PORT}:27017"
    networks:
      - test_network

networks:
  test_network: