name: Deploy-pre-prod

on:
  push:
    branches: [develop]

  workflow_dispatch:

jobs:
  deploy-pre-prod:
    environment: pre-prod
    env:
      ENV_NAME: pre-prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update Pre-Prod Docker in server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PWD }}
          port: ${{ secrets.SERVER_PORT }}
          script_stop: true
          script: |
            cd /var/www/test
            git checkout develop
            git pull
            sudo docker-compose up -d --build -e ENV_NAME=${{ env.ENV_NAME }}