name: Deploy-pre-prod

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branches
  push:
    branches: [develop]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-pre-prod:
    environment: pre-prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update Pre-Prod Docker in server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PWD }}
          port: ${{ secrets.SERVER_PORT }}
          script_stop: true
          script: |
            cd /var/www/test
            git checkout develop
            git pull
            sudo docker-compose up -d --build