name: Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Rename main Git branch
        run: git config --global init.defaultBranch
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          tags: iim-a4-ci-cd_nextjs:latest
          push: false
      - name: Lint project
        uses: addnab/docker-run-action@v3
        with:
          image: iim-a4-ci-cd_nextjs:latest
          run: yarn lint
