name: Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker image
        run: docker-compose up -d --build
      - name: Lint project
        - uses: actions/checkout@v2
        - uses: addnab/docker-run-action@v3
          with:
            image: iim-a4-ci-cd_nextjs:latest
            run: yarn lint
